apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-petclinic-gitops-03
  labels:
    app.kubernetes.io/part-of: petclinic-server
    apps.kubernetes.io/name: spring-petclinic-gitops
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: spring-petclinic-gitops-03
spec:
  template:
    metadata:
      annotations:
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          appliveview-sample/app-live-view-connector-boot
          appliveview-sample/app-live-view-appflavours-boot
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: petclinic-server
        apps.kubernetes.io/name: spring-petclinic-gitops
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: spring-petclinic-gitops-03
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: spring-petclinic-gitops-03
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: mysql
        - name: JAVA_TOOL_OPTIONS
          value: |-
            -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9005
             -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.exposure.include=* -Dspring.devtools.restart.enabled=true -Dspring.devtools.restart.poll-interval=2s -Dspring.devtools.restart.quiet-period=1s
        image: cloudfocusedreg.azurecr.io/tap-integration-repo/msrinivasssa/apps/spring-petclinic-gitops-03-my-apps@sha256:741d27b0a92fb2097f8dde2f9bbf15f1b1e40f952793fa3ee0465fa3f6fb37c0
        name: workload
        resources:
          limits:
            cpu: "4"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

